server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Вот эта строчка чинит 404 ошибку для react-router-dom:
        try_files $uri $uri/ /index.html; 
    }
}